// Generated by CoffeeScript 1.6.2
(function() {
  var app, express;

  express = require('express');

  app = module.exports = express();

  app.set('view engine', 'jade');

  app.set('views', "" + __dirname + "/views");

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(app.router);

  app.get('/', function(req, res) {
    return res.render('home');
  });

}).call(this);
